name: test
on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - developer-dir: "/Applications/Xcode_14.0.1.app"
            sdk: "iphonesimulator16.0"
            scheme: "HTMLReader iOS"
            destination: "OS=16.0,name=iPhone 14"
            action: "test"
          - developer-dir: "/Applications/Xcode_14.0.1.app"
            sdk: "macosx12.3"
            scheme: "HTMLReader OS X"
            destination: "arch=x86_64"
            action: "test"
          - developer-dir: "/Applications/Xcode_14.0.1.app"
            sdk: "appletvsimulator16.0"
            scheme: "HTMLReader tvOS"
            destination: "OS=16.0,name=Apple TV"
            action: "test"
          - developer-dir: "/Applications/Xcode_13.4.1.app"
            sdk: "iphonesimulator15.5"
            scheme: "HTMLReader iOS"
            destination: "OS=15.5,name=iPhone 13"
            action: "test"
          - developer-dir: "/Applications/Xcode_13.4.1.app"
            sdk: "appletvsimulator15.4"
            scheme: "HTMLReader tvOS"
            destination: "OS=15.4,name=Apple TV"
            action: "test"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: xcodebuild
        env:
          DEVELOPER_DIR: ${{ matrix.developer-dir }}
        run: xcodebuild -project HTMLReader.xcodeproj -scheme "${{ matrix.scheme }}" -configuration Release -sdk "${{ matrix.sdk }}" -destination "${{ matrix.destination }}" "${{ matrix.action }}"
